### PR TITLE
MAGE-348 - Adapted browser back button solution to cancel redirect pa…

### PR DESCRIPTION
**Pull request by FatchipRobert**
…ymebt solution

### CODE REVIEW

**Comment by sprankhub** [comment]
What does this exactly fix?

**Comment by sprankhub** [comment]
Background: We have weird "911: Reference number already exists" issues with version 4.1.5 and payments without orders. I hope that this commit solves them, but maybe this is totally unrelated...

**Comment by FatchipRobert** [comment]
Hmm no - I thinks this is not related.
This fixed following scenario:
Customer choses a redirect payment-method and was redirected to the payment-provider, then the customer uses the browser-back-button to jump back to the shop ( the order is being canceled ) and then the user uses the browser-forward-button to jump back to the payment-provider and finishes the payment.
Pre-fix this would result in a payed but canceled order.
Post-fix the canceled order stays canceled, but a new substitute-order is created and all the TransactionStatuses are rerouted to the new order.

**Comment by fjbender** [comment]
@sprankhub I suppose the "Reference number already exists" error is related to an incident on our platform yesterday where transaction processing was delayed by up to 60 seconds - the order timed out (and subsequently wasn't created in Magento) but payment was initiated anyway.

**Pull request merged**
